default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: cheetah
  host: localhost
  username: hanan
  password: 123qwe

test:
  <<: *default
  database: cheetah_test
